In [1]:
import numpy as np
import matplotlib.pyplot as plt
import rayleigh_diagnostics_main as main
import rayleigh_diagnostics_brad as brad

Brads version of Shell_Spectra


In [10]:
fname = '09430000'
spec_main = main.Shell_Spectra(fname,'')
spec_brad = brad.Shell_Spectra(fname,'')

Brads version of Shell_Spectra (init)


In [14]:
# first let's make sure they display basically the same metadata
spec_main.print_info()

version  :  5
niter    :  1
nq       :  8
nr       :  9
nell     :  256
nm       :  256
lmax     :  255
mmax     :  255
.......................
radius   :  [4.10205516 4.02052516 3.90708579 3.77150636 3.65818196 3.52849364
 3.39291421 3.27947484 3.19794484]
.......................
rad_inds :  [13 22 31 40 47 55 64 73 82]
.......................
iters    :  [9430000]
.......................
time     :  [165627.70962948]
.......................
qv       :  [  1   2   3 301 302 303 501 502]


In [15]:
spec_brad.print_info()

version  :  5
niter    :  1
nq       :  8
nr       :  9
nell     :  256
nm       :  256
lmax     :  255
mmax     :  255
.......................
radius   :  [4.10205516 4.02052516 3.90708579 3.77150636 3.65818196 3.52849364
 3.39291421 3.27947484 3.19794484]
.......................
rad_inds :  [13 22 31 40 47 55 64 73 82]
.......................
iters    :  [9430000]
.......................
time     :  [165627.70962948]
.......................
qv       :  [  1   2   3 301 302 303 501 502]


In [16]:
# sweet!

In [26]:
# now let's check if all the values are the same
vals_diff = spec_main.vals - spec_brad.vals
lpower_diff = spec_main.lpower - spec_brad.lpower
lut_diff = spec_main.lut - spec_brad.lut
print("total 'vals'   difference:", np.sum(np.abs(vals_diff)**2))
print("total 'lpower' difference:", np.sum(np.abs(lpower_diff)))
print("total 'lut'    difference:", np.sum(np.abs(lut_diff)))

total 'vals'   difference: 0.0
total 'lpower' difference: 8.039916866783373e-15
total 'lut'    difference: 0


In [23]:
# ok, pretty good! Although it means even the default computation of l-values is slightly different in Brad's version
# but it matches to machine precision, so ok

In [25]:
# now read in two small random 5x10 section of the power for some quantity: one at the "edge" of the array
# and one at the "middle" somewhere
# read these from the "main" version to serve as the benchmark when we test partial reading
print(np.shape(spec_main.vals))

(256, 256, 9, 8, 1)


In [28]:
section_edge = spec_main.vals[:5, :10, 0, 0, 0]
irval = 3
iqval = 5
section_middle = spec_main.vals[22:27, 33:43, irval, iqval, 0]
print("chosen quantity:", spec_main.qv[iqval]) # phi vorticity

chosen quantity: 303


In [37]:
# now let's see if Brad's thing works!
spec_edge = brad.Shell_Spectra(fname, '', lset=np.arange(5), mset=np.arange(10), irset=0, qvset=1, iterset=0)
spec_middle = brad.Shell_Spectra(fname, '', lset=np.arange(22,27), mset=np.arange(33,43), irset=irval, qvset=303, iterset=0)

Brads version of Shell_Spectra (init)
Brads version of Shell_Spectra (init)


In [38]:
np.shape(spec_edge.vals)

(5, 10, 1, 1, 1)

In [39]:
spec_edge.vals[:,:,0,0,0] - section_edge

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j]])

In [41]:
spec_middle.vals[:,:,0,0,0] - section_middle

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j]])

In [42]:
# sweet that works!

In [43]:
# now try getting the same slice in a weird way (multiple qvals in reverse order, multiple radii
# in scrambled order (and one repeated), more mvals and lvals than we need, as lists
spec_middle_scrambled = brad.Shell_Spectra(fname, '', lset=np.arange(20,45).tolist(),\
                        mset=np.arange(30,45).tolist(), irset=[0,8,irval,2,2], qvset=[502,303,301], iterset=0)

Brads version of Shell_Spectra (init)


In [48]:
np.shape(spec_middle_scrambled.vals)
print(spec_middle_scrambled.radius)
print(spec_main.radius)
print(spec_main.radius[irval])

[4.10205516 3.90708579 3.77150636 3.19794484]
[4.10205516 4.02052516 3.90708579 3.77150636 3.65818196 3.52849364
 3.39291421 3.27947484 3.19794484]
3.77150635504632


In [50]:
# oh nice it removed the repeated radius and sorted everything!
# should have remembered that

# I guess the same is true of the qvals? 
print(spec_middle_scrambled.qv)
print(spec_main.qv)
print(spec_main.qv[iqval])

[301 303 502]
[  1   2   3 301 302 303 501 502]
303


In [51]:
# yes everything is sorted

# see if the same values are contained now
# lvals: start at index 2
# mvals: start at index 3
# radius index: 2
# qvals index: 1
section_middle_scrambled = spec_middle_scrambled.vals[2:7,3:13, 2, 1, 0]
section_middle_scrambled - section_middle

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j]])

In [52]:
# OK I am satisfied this is behaving well!

In [53]:
# now try to break stuff and see what happens