In [1]:
import numpy as np
import matplotlib.pyplot as plt
import rayleigh_diagnostics_main as main
import rayleigh_diagnostics_brad_v3 as brad

In [2]:
fname = '09430000'
spec_main = main.Shell_Spectra(fname,'')
spec_brad = brad.Shell_Spectra(fname,'')

In [3]:
# first let's make sure they display basically the same metadata
spec_main.print_info()

version  :  5
niter    :  1
nq       :  8
nr       :  9
nell     :  256
nm       :  256
lmax     :  255
mmax     :  255
.......................
radius   :  [4.10205516 4.02052516 3.90708579 3.77150636 3.65818196 3.52849364
 3.39291421 3.27947484 3.19794484]
.......................
rad_inds :  [13 22 31 40 47 55 64 73 82]
.......................
iters    :  [9430000]
.......................
time     :  [165627.70962948]
.......................
qv       :  [  1   2   3 301 302 303 501 502]


In [4]:
spec_brad.print_info()

version  :  5
niter    :  1
nq       :  8
nr       :  9
nell     :  256
nm       :  256
lmax     :  255
mmax     :  255
.......................
radius   :  [4.10205516 4.02052516 3.90708579 3.77150636 3.65818196 3.52849364
 3.39291421 3.27947484 3.19794484]
.......................
rad_inds :  [13 22 31 40 47 55 64 73 82]
.......................
m        :  [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 

In [5]:
# sweet!

In [6]:
# now let's check if all the values are the same
vals_diff = spec_main.vals - spec_brad.vals
lpower_diff = spec_main.lpower - spec_brad.lpower
lut_diff = spec_main.lut - spec_brad.lut
print("total 'vals'   difference:", np.sum(np.abs(vals_diff)**2))
print("total 'lpower' difference:", np.sum(np.abs(lpower_diff)))
print("total 'lut'    difference:", np.sum(np.abs(lut_diff)))

total 'vals'   difference: 0.0
total 'lpower' difference: 8.039916866783373e-15
total 'lut'    difference: 0


In [7]:
# ok, pretty good! Although it means even the default computation of l-values is slightly different in Brad's version
# but it matches to machine precision, so ok

In [8]:
# now read in two small random 5x10 section of the power for some quantity: one at the "edge" of the array
# and one at the "middle" somewhere
# read these from the "main" version to serve as the benchmark when we test partial reading
print(np.shape(spec_main.vals))

(256, 256, 9, 8, 1)


In [9]:
section_edge = spec_main.vals[:5, :10, 0, 0, 0]
irval = 3
iqval = 5
section_middle = spec_main.vals[22:27, 33:43, irval, iqval, 0]
print("chosen quantity:", spec_main.qv[iqval]) # phi vorticity

chosen quantity: 303


In [10]:
# now let's see if Brad's thing works!
spec_edge = brad.Shell_Spectra(fname, '', lset=np.arange(5), mset=np.arange(10), irset=0, qvset=1, iterset=0)
spec_middle = brad.Shell_Spectra(fname, '', lset=np.arange(22,27), mset=np.arange(33,43), irset=irval, qvset=303, iterset=0)

In [11]:
np.shape(spec_edge.vals)

(5, 10, 1, 1, 1)

In [12]:
spec_edge.vals[:,:,0,0,0] - section_edge

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j]])

In [13]:
spec_middle.vals[:,:,0,0,0] - section_middle

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j]])

In [14]:
# sweet that works!

In [15]:
# now try getting the same slice in a weird way (multiple qvals in reverse order, multiple radii
# in scrambled order (and one repeated), more mvals and lvals than we need, as lists
spec_middle_scrambled = brad.Shell_Spectra(fname, '', lset=np.arange(20,45).tolist(),\
                        mset=np.arange(30,45).tolist(), irset=[0,8,irval,2,2], qvset=[502,303,301], iterset=0)

In [16]:
np.shape(spec_middle_scrambled.vals)
print(spec_middle_scrambled.radius)
print(spec_main.radius)
print(spec_main.radius[irval])

[4.10205516 3.90708579 3.77150636 3.19794484]
[4.10205516 4.02052516 3.90708579 3.77150636 3.65818196 3.52849364
 3.39291421 3.27947484 3.19794484]
3.77150635504632


In [17]:
# oh nice it removed the repeated radius and sorted everything!
# should have remembered that

# I guess the same is true of the qvals? 
print(spec_middle_scrambled.qv)
print(spec_main.qv)
print(spec_main.qv[iqval])

[301 303 502]
[  1   2   3 301 302 303 501 502]
303


In [18]:
# yes everything is sorted

# see if the same values are contained now
# lvals: start at index 2
# mvals: start at index 3
# radius index: 2
# qvals index: 1
section_middle_scrambled = spec_middle_scrambled.vals[2:7,3:13, 2, 1, 0]
section_middle_scrambled - section_middle

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j]])

In [19]:
# OK I am satisfied this is behaving well!

In [20]:
# now try to break stuff and see what happens

In [21]:
spec_bad = brad.Shell_Spectra(fname, '', lset=np.pi,\
                        mset=np.arange(30,45).tolist(), irset=[0,8,irval,2,2], qvset=[502,303,301], iterset=0)
print(spec_bad.qv)
print(np.shape(spec_bad.vals))
print(spec_bad.l)

[301 303 502]
(1, 15, 4, 3, 1)
[3]


In [22]:
# hmmm...IDK if we want that. Maybe it should just initialize a spectrum with empty attributes? 
# I feel like all Shell_Spectra should be the same

In [23]:
# let's try to trick it with an integer that is a float
spec_bad = brad.Shell_Spectra(fname, '', lset=1.,\
                        mset=np.arange(30,45).tolist(), irset=[0,8,irval,2,2], qvset=[502,303,301], iterset=0)
print(spec_bad.qv)

[301 303 502]


In [24]:
# OK that's good it doesn't like it, but it also throws a Python error, not a Brad error
# also, maybe lvals SHOULD be allowed to be "integer" floats like 1.0? 

In [25]:
# I guess that could cause problems by making weird numbers into "ints" though...hmmm....
0.9999999999999999999999999999999999999999999999999999

1.0

In [26]:
# let's try making all sets = np.py
spec_bad = brad.Shell_Spectra(fname, '', lset=np.pi,\
                        mset=np.pi, irset=np.pi, qvset=np.pi, iterset=0)
print(spec_bad.qv)

[3]


In [27]:
# OK that's good! But I feel like it should also do the same for 1.0 (or else convert to an int and have it allowable)

In [28]:
# see if other variables behave the same way for non-ints like 1.0
spec_bad = brad.Shell_Spectra(fname, '', lset=np.arange(20,45).tolist(),\
                        mset=1.0, irset=[0,8,irval,2,2], qvset=[502,303,301], iterset=0)
print(spec_bad.qv)

[301 303 502]


In [29]:
# try 1.09
spec_bad = brad.Shell_Spectra(fname, '', lset=np.arange(20,45).tolist(),\
                        mset=1.09, irset=[0,8,irval,2,2], qvset=[502,303,301], iterset=0)
print(spec_bad.qv)

[301 303 502]


In [30]:
# hmmm... the errors seem fine as long as the float is not secretly an int....

In [31]:
# let's try to trick it with a machine precision "int" that's definitely a float....
spec_bad = brad.Shell_Spectra(fname, '', lset=np.arange(20,45).tolist(),\
                        mset=0.999999999999999999999999999999999, irset=[0,8,irval,2,2], qvset=[502,303,301], iterset=0)
print(spec_bad.qv)

[301 303 502]


In [32]:
# yep that's the same as 1.0, to be expected

In [33]:
# check the other indices
spec_bad = brad.Shell_Spectra(fname, '', lset=np.arange(20,45).tolist(),\
                        mset=1, irset=1.0, qvset=[502,303,301], iterset=0)
print(spec_bad.qv)

[301 303 502]


In [34]:
# check the other indices
spec_bad = brad.Shell_Spectra(fname, '', lset=np.arange(20,45).tolist(),\
                        mset=1, irset=1, qvset=1.0, iterset=0)
print(spec_bad.qv)

[1]


In [35]:
# interesting that one throws a different error
spec_bad = brad.Shell_Spectra(fname, '', lset=np.arange(20,45).tolist(),\
                        mset=1, irset=1, qvset=1, iterset=0.0)
print(spec_bad.qv)

[1]


In [36]:
# huh! iterset doesn't behave this way...it treats the float as an int

In [37]:
# try a real float for iterset
spec_bad = brad.Shell_Spectra(fname, '', lset=np.arange(20,45).tolist(),\
                        mset=1, irset=1, qvset=1, iterset=0.05)
print(spec_bad.qv)

[1]


In [38]:
# OK all I've learned is that the errors are inconsistent (except for iterset with nrec=1)
# between when a float is passed vs. a float that's really an int

In [39]:
# let's see what happens when a list is past containing one "float" that's really an int
spec_bad = brad.Shell_Spectra(fname, '', lset=[0,3,4, 16, 20.0, 30, 35],\
                        mset=1, irset=1, qvset=1, iterset=0)
print(spec_bad.qv)

[1]


In [40]:
# same thing...try for a real float in the list
spec_bad = brad.Shell_Spectra(fname, '', lset=[0,3,4, 16, 20.7, 30, 35],\
                        mset=1, irset=1, qvset=1, iterset=0)
print(spec_bad.qv)

[1]


In [41]:
# aha! Now it tries to return the "found" indices but then fails on the single (real) float!
# probably we should just have it ignore the float and not complain? 
# or maybe it should just cast everything to ints IDK
# it doesn't really matter, the user should not be messing with floats ;-p

In [42]:
# OK loren is sick of messing with floats
# try to get it to read l-values that don't exist
spec_bad = brad.Shell_Spectra(fname, '', lset=-4,\
                        mset=1, irset=1, qvset=1, iterset=0)
print(spec_bad.qv)

 
---------------------------------------------------------
 ERROR: Requested harmonic degrees not found
 Specified degrees:  [-4]
 Available degrees:  [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 

In [65]:
# now loren will be a jerk and try to get it to read negative m
# (which really by all rights should be the complex conjugate of the positive m values :)
spec_bad = brad.Shell_Spectra(fname, '', lset=4,\
                        mset=-3, irset=1, qvset=1, iterset=0)
print(spec_bad.qv)
help(spec_bad)

 
---------------------------------------------------------
 ERROR: Requested azimuthal orders not found
 Specified orders:  [-3]
 Available orders:  [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 20

In [66]:
dir(spec_bad)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'inds',
 'iters',
 'l',
 'lmax',
 'lpower',
 'lut',
 'm',
 'mmax',
 'nell',
 'niter',
 'nm',
 'nq',
 'nr',
 'print_info',
 'qv',
 'rad_inds',
 'radius',
 'time',
 'vals',
 'version']

In [70]:
print(spec_bad.time)
print(spec_bad.iters)
print(spec_bad.l)
print(spec_bad.m)
print(spec_bad.lmax)
print(spec_bad.mmax)
print(spec_bad.nm)
print(spec_bad.nell)
print(np.shape(spec_bad.vals))
print(np.shape(spec_bad.lpower))

[]
[]
[4]
[]
255
255
0
1
(0,)
(0,)


In [52]:
# aha! No complex conjugation :)

In [53]:
# try to get it to read some values out of range...presumably it will only read the actual ones

In [54]:
spec_bad = brad.Shell_Spectra(fname, '', lset=[-1,4,6,33,65,202,544],\
                        mset=np.array([3,16,43,95]), irset=1, qvset=1, iterset=0)
print(np.shape(spec_bad.vals))

 
---------------------------------------------------------
 Invalid degrees requested:  [ -1 544]
 Valid degrees requested:  [  4   6  33  65 202]
 Available degrees:  [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204

In [55]:
# OK I think that's all fine then...

In [56]:
# I'm just going to test the lpower on that "bad" slice and then quit :)

In [57]:
lpower_lorens_opinion = np.sum(np.abs(spec_bad.vals[...,0,0,0])**2, axis=1)
print(np.shape(spec_bad.lpower))

(5, 1, 1, 1, 3)


In [58]:
#m = 0 wasn't requested so it should be zero
# the other lpowers should be equal to mine
print(lpower_lorens_opinion)
print(spec_bad.lpower[:,0,0,0,0])
print(spec_bad.lpower[:,0,0,0,1])
print(spec_bad.lpower[:,0,0,0,2])

[1.33229743e-07 1.64114428e-09 9.54991498e-07 2.06118905e-06
 2.17109793e-08]
[1.33229743e-07 1.64114428e-09 9.54991498e-07 2.06118905e-06
 2.17109793e-08]
[0. 0. 0. 0. 0.]
[1.33229743e-07 1.64114428e-09 9.54991498e-07 2.06118905e-06
 2.17109793e-08]


In [59]:
# ok all looks good!

In [60]:
# EXCEPT: the complex power really should NOT be multiplied by sqrt(2) in the first place
# I feel like that's an issue with the main code...really all the negative m-values are the complex conjugate
# of the positive m-values
# I don't know, it's probably not worth bugging Nick about it, I guess it's just a convention
# in the cross spectra, I guess it's all fine? We are looking for real quantities eventually (always?)
# but then for waves, once we take another Fourier transform (in time), maybe it does matter? 
# I don't know my brain is scrambled....

In [61]:
# Update 07/15/26
# OK Brad has resolved this for me I think!